[build]
  command = "npm run build"
  # Aquí es donde Nitro (con el preset netlify) exporta los recursos del cliente
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_PNPM = "false"
  NPM_FLAGS = "--legacy-peer-deps"